version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
  kafka:
    image: wurstmeister/kafka:2.12-2.3.0
    links:
     - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "order:1:1,orderStatus:1:1"
   
  apache:
    build: apache
    links:
     - order
     - fulfillment
     - fulfillment1
    ports:
     - "8080:80"
  postgres:
    build: postgres
    environment:
      POSTGRES_PASSWORD: dbpass
      POSTGRES_USER: dbuser
  order:
    build: ../order-mgmt-app
    links:
     - kafka
     - postgres
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  fulfillment:
    build: ../order-fulflmnt-app
    links:
     - kafka
     - postgres
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  fulfillment1:
    build: ../order-fulflmnt1-app
    links:
     - kafka
     - postgres
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

